name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/shape_1.png
  - assets/vectors/wifi_x2.svg
  - assets/vectors/cellular_connection_x2.svg
  - assets/vectors/battery_x2.svg
  - assets/images/unsplashp_at_a_8_xe_ivm.jpeg
  - assets/images/mesh_gradient_1.png
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/graph_eth_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/group_48095464_x2.svg
  - assets/vectors/divider_2_x2.svg
  - assets/vectors/cellular_connection_2_x2.svg
  - assets/vectors/xrp_x2.svg
  - assets/vectors/graph_eth_2_x2.svg
  - assets/vectors/graph_btc_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/graph_eth_1_x2.svg
  - assets/vectors/eth_icon_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/arrow_up_x2.svg
  - assets/vectors/battery_3_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/wifi_3_x2.svg
  - assets/vectors/line_copy_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/divider_x2.svg
  - assets/vectors/line_copy_1_x2.svg
  - assets/vectors/group_5_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/cellular_connection_3_x2.svg
  - assets/vectors/vector_12_x2.svg

